import { db } from '@/lib/db/dexie-db';
import type { Collection, Endpoint, KeyValue } from '@/types';

// ═══════════════════════════════════════════════════
// 12-Endpoint Pre-seeded "Enterprise Storefront API"
// ═══════════════════════════════════════════════════
const SEED_COLLECTION: Collection = {
  id: 'col-enterprise-1',
  name: 'Enterprise Storefront API',
  description: 'A complete e-commerce backend simulation with Auth, Users, Orders & Products.',
  baseUrl: 'https://api.enterprise.dev',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const makeKV = (pairs: [string, string][]): KeyValue[] =>
  pairs.map(([key, value], i) => ({ id: `kv-${i}`, key, value, enabled: true }));

const SEED_ENDPOINTS: Omit<Endpoint, 'collectionId'>[] = [
  // ── AUTH ──────────────────────────────────────────
  {
    id: 'ep-auth-login',
    name: 'User Login',
    method: 'POST',
    path: '/api/v1/auth/login',
    summary: 'Authenticate user credentials and issue JWT session token',
    resource: 'Authentication',
    authRequired: false,
    queryParams: [],
    pathParams: [],
    headers: makeKV([['Content-Type', 'application/json']]),
    requestBody: JSON.stringify({ email: 'alex.chen@enterprise.dev', password: 'Password123!' }, null, 2),
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ep-auth-refresh',
    name: 'Refresh Token',
    method: 'POST',
    path: '/api/v1/auth/refresh',
    summary: 'Exchange refresh token for a new access token',
    resource: 'Authentication',
    authRequired: false,
    queryParams: [],
    pathParams: [],
    headers: makeKV([['Content-Type', 'application/json']]),
    requestBody: JSON.stringify({ refresh_token: 'rt_placeholder_token' }, null, 2),
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ep-auth-logout',
    name: 'Logout',
    method: 'DELETE',
    path: '/api/v1/auth/logout',
    summary: 'Invalidate current session and revoke tokens',
    resource: 'Authentication',
    authRequired: true,
    queryParams: [],
    pathParams: [],
    headers: makeKV([['Authorization', 'Bearer {{token}}']]),
    requestBody: '',
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // ── USERS ─────────────────────────────────────────
  {
    id: 'ep-users-list',
    name: 'List Users',
    method: 'GET',
    path: '/api/v1/users',
    summary: 'Retrieve paginated list of organizational users',
    resource: 'Users',
    authRequired: true,
    queryParams: makeKV([['page', '1'], ['limit', '10'], ['role', 'admin']]),
    pathParams: [],
    headers: makeKV([['Authorization', 'Bearer {{token}}']]),
    requestBody: '',
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ep-users-get',
    name: 'Get User',
    method: 'GET',
    path: '/api/v1/users/:id',
    summary: 'Retrieve a single user by their unique identifier',
    resource: 'Users',
    authRequired: true,
    queryParams: [],
    pathParams: makeKV([['id', 'usr_44e1b99a']]),
    headers: makeKV([['Authorization', 'Bearer {{token}}']]),
    requestBody: '',
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ep-users-update',
    name: 'Update User',
    method: 'PUT',
    path: '/api/v1/users/:id',
    summary: 'Update user profile details',
    resource: 'Users',
    authRequired: true,
    queryParams: [],
    pathParams: makeKV([['id', 'usr_44e1b99a']]),
    headers: makeKV([['Authorization', 'Bearer {{token}}'], ['Content-Type', 'application/json']]),
    requestBody: JSON.stringify({ name: 'Alex Chen', email: 'alex.chen@enterprise.dev', role: 'admin' }, null, 2),
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ep-users-delete',
    name: 'Delete User',
    method: 'DELETE',
    path: '/api/v1/users/:id',
    summary: 'Permanently remove a user account',
    resource: 'Users',
    authRequired: true,
    queryParams: [],
    pathParams: makeKV([['id', 'usr_44e1b99a']]),
    headers: makeKV([['Authorization', 'Bearer {{token}}']]),
    requestBody: '',
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // ── ORDERS ────────────────────────────────────────
  {
    id: 'ep-orders-list',
    name: 'List Orders',
    method: 'GET',
    path: '/api/v1/orders',
    summary: 'Retrieve paginated order history with filters',
    resource: 'Orders',
    authRequired: true,
    queryParams: makeKV([['page', '1'], ['limit', '20'], ['status', 'pending']]),
    pathParams: [],
    headers: makeKV([['Authorization', 'Bearer {{token}}']]),
    requestBody: '',
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ep-orders-create',
    name: 'Create Order',
    method: 'POST',
    path: '/api/v1/orders',
    summary: 'Create new customer checkout order',
    resource: 'Orders',
    authRequired: true,
    queryParams: [],
    pathParams: [],
    headers: makeKV([['Authorization', 'Bearer {{token}}'], ['Content-Type', 'application/json']]),
    requestBody: JSON.stringify({
      customer_id: 'usr_44e1b99a',
      amount: 149.50,
      currency: 'USD',
      items: [{ sku: 'PRD-099', quantity: 2, price: 74.75 }],
    }, null, 2),
    mockScenario: 201,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ep-orders-get',
    name: 'Get Order',
    method: 'GET',
    path: '/api/v1/orders/:id',
    summary: 'Retrieve detailed information for a specific order',
    resource: 'Orders',
    authRequired: true,
    queryParams: [],
    pathParams: makeKV([['id', 'ord_88f1a0']]),
    headers: makeKV([['Authorization', 'Bearer {{token}}']]),
    requestBody: '',
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ep-orders-cancel',
    name: 'Cancel Order',
    method: 'DELETE',
    path: '/api/v1/orders/:id',
    summary: 'Cancel and initiate refund for an unfulfilled order',
    resource: 'Orders',
    authRequired: true,
    queryParams: [],
    pathParams: makeKV([['id', 'ord_88f1a0']]),
    headers: makeKV([['Authorization', 'Bearer {{token}}']]),
    requestBody: '',
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // ── PRODUCTS ──────────────────────────────────────
  {
    id: 'ep-products-list',
    name: 'Product Catalog',
    method: 'GET',
    path: '/api/v1/products',
    summary: 'Browse full product catalog with search and category filters',
    resource: 'Products',
    authRequired: false,
    queryParams: makeKV([['page', '1'], ['limit', '24'], ['category', 'electronics'], ['sort', 'price_asc']]),
    pathParams: [],
    headers: [],
    requestBody: '',
    mockScenario: 200,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ═══════════════════════════════════════════════════
// Seed function — runs once on first launch
// ═══════════════════════════════════════════════════
export async function seedDatabase(): Promise<void> {
  const existingCollections = await db.collections.count();
  if (existingCollections > 0) return; // Already seeded

  await db.collections.add(SEED_COLLECTION);
  await db.endpoints.bulkAdd(
    SEED_ENDPOINTS.map(ep => ({ ...ep, collectionId: SEED_COLLECTION.id }))
  );
  console.log('[APIFlow] Database seeded with Enterprise Storefront API');
}
