import type { Collection, Endpoint, KeyValue } from '@/types';

export interface ApiTemplate {
  id: string;
  name: string;
  category: 'Fintech' | 'AI / LLM' | 'SaaS' | 'E-Commerce';
  icon: string;
  description: string;
  endpointCount: number;
  collection: Collection;
  endpoints: Omit<Endpoint, 'collectionId'>[];
}

const makeKV = (pairs: [string, string][]): KeyValue[] =>
  pairs.map(([key, value], i) => ({ id: `kv-${i}-${Date.now()}`, key, value, enabled: true }));

export const PRESET_TEMPLATES: ApiTemplate[] = [
  // ── 1. STRIPE BILLING & PAYMENTS ────────────────────────────────
  {
    id: 'tpl-stripe',
    name: 'Stripe Billing & Payments',
    category: 'Fintech',
    icon: 'CreditCard',
    description: 'Realistic payment intents, customer cards, invoice generation & webhook simulation.',
    endpointCount: 5,
    collection: {
      id: 'col-stripe-payments',
      name: 'Stripe Payments API',
      description: 'End-to-end checkout, authorization, capture & webhook lifecycle.',
      baseUrl: 'https://api.stripe.com',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    endpoints: [
      {
        id: 'ep-stripe-create-intent',
        name: 'Create PaymentIntent',
        method: 'POST',
        path: '/v1/payment_intents',
        summary: 'Create PaymentIntent to initiate a checkout transaction',
        resource: 'Payments',
        authRequired: true,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Authorization', 'Bearer {{stripe_secret_key}}'], ['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          amount: 4999,
          currency: 'usd',
          customer: 'cus_99axz01',
          payment_method_types: ['card'],
          description: 'APIFlow Pro Monthly Subscription',
        }, null, 2),
        mockScenario: 201,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-stripe-get-intent',
        name: 'Get PaymentIntent',
        method: 'GET',
        path: '/v1/payment_intents/:id',
        summary: 'Retrieve status and card charge authorization result',
        resource: 'Payments',
        authRequired: true,
        queryParams: [],
        pathParams: makeKV([['id', 'pi_3MtwBwLkdIwHu7ix28a3tqPa']]),
        headers: makeKV([['Authorization', 'Bearer {{stripe_secret_key}}']]),
        requestBody: '',
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-stripe-create-customer',
        name: 'Create Customer',
        method: 'POST',
        path: '/v1/customers',
        summary: 'Create customer profile and attach billing email',
        resource: 'Customers',
        authRequired: true,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Authorization', 'Bearer {{stripe_secret_key}}'], ['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          name: 'Sarah Connor',
          email: 'sarah.connor@cyberdyne.io',
          phone: '+1 555-0199',
          metadata: { plan: 'growth_tier' },
        }, null, 2),
        mockScenario: 201,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-stripe-list-invoices',
        name: 'List Customer Invoices',
        method: 'GET',
        path: '/v1/invoices',
        summary: 'Retrieve paginated customer receipts & invoices',
        resource: 'Billing',
        authRequired: true,
        queryParams: makeKV([['customer', 'cus_99axz01'], ['status', 'paid'], ['limit', '10']]),
        pathParams: [],
        headers: makeKV([['Authorization', 'Bearer {{stripe_secret_key}}']]),
        requestBody: '',
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-stripe-webhook',
        name: 'Simulate Stripe Webhook',
        method: 'POST',
        path: '/api/webhooks/stripe',
        summary: 'Deliver payment_intent.succeeded event to app server',
        resource: 'Webhooks',
        authRequired: false,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Stripe-Signature', 't=1614000000,v1=5257a869e7ecebeda32affa62cd4...'], ['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          id: 'evt_1MtwBwLkdIwHu7ix28a3tqPa',
          type: 'payment_intent.succeeded',
          created: 1614000000,
          data: {
            object: {
              id: 'pi_3MtwBwLkdIwHu7ix28a3tqPa',
              amount: 4999,
              currency: 'usd',
              status: 'succeeded',
            },
          },
        }, null, 2),
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },

  // ── 2. OPENAI & LLM API ──────────────────────────────────────────
  {
    id: 'tpl-openai',
    name: 'OpenAI & LLM API',
    category: 'AI / LLM',
    icon: 'Bot',
    description: 'Chat completions, streaming schemas, embeddings, and model capability listings.',
    endpointCount: 3,
    collection: {
      id: 'col-openai-llm',
      name: 'OpenAI API v1',
      description: 'Generative AI chat models, embeddings, and reasoning endpoints.',
      baseUrl: 'https://api.openai.com',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    endpoints: [
      {
        id: 'ep-openai-chat',
        name: 'Create Chat Completion',
        method: 'POST',
        path: '/v1/chat/completions',
        summary: 'Generate AI response with system/user prompt messages',
        resource: 'Chat',
        authRequired: true,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Authorization', 'Bearer {{openai_api_key}}'], ['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          model: 'gpt-4o',
          messages: [
            { role: 'system', content: 'You are an expert full-stack developer assistance agent.' },
            { role: 'user', content: 'Explain how CORS proxies prevent browser origin blocking.' },
          ],
          temperature: 0.7,
          max_tokens: 500,
        }, null, 2),
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-openai-models',
        name: 'List Models',
        method: 'GET',
        path: '/v1/models',
        summary: 'List available model weights and context windows',
        resource: 'Models',
        authRequired: true,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Authorization', 'Bearer {{openai_api_key}}']]),
        requestBody: '',
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-openai-embeddings',
        name: 'Create Embeddings',
        method: 'POST',
        path: '/v1/embeddings',
        summary: 'Generate 1536-dimensional vector for semantic search',
        resource: 'Embeddings',
        authRequired: true,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Authorization', 'Bearer {{openai_api_key}}'], ['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          input: 'Semantic retrieval of API contract schemas in vector space',
          model: 'text-embedding-3-small',
        }, null, 2),
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },

  // ── 3. SAAS AUTH & RBAC IAM ──────────────────────────────────────
  {
    id: 'tpl-saas-auth',
    name: 'SaaS Auth & Multi-Tenant IAM',
    category: 'SaaS',
    icon: 'ShieldCheck',
    description: 'OAuth2 / JWT sessions, refresh tokens, role checks, and organization member invites.',
    endpointCount: 5,
    collection: {
      id: 'col-saas-iam',
      name: 'SaaS Authentication & RBAC',
      description: 'Enterprise multi-tenant authentication, password reset & permission management.',
      baseUrl: 'https://auth.acmecorp.dev',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    endpoints: [
      {
        id: 'ep-auth-register',
        name: 'Register Organization User',
        method: 'POST',
        path: '/api/v1/auth/register',
        summary: 'Register new workspace administrator account',
        resource: 'Authentication',
        authRequired: false,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          orgName: 'Acme Robotics',
          email: 'founder@acmerobotics.dev',
          password: 'Password123#Secure',
        }, null, 2),
        mockScenario: 201,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-auth-login-saas',
        name: 'User Login & Session Token',
        method: 'POST',
        path: '/api/v1/auth/login',
        summary: 'Exchange credentials for JWT Bearer token and refresh cookie',
        resource: 'Authentication',
        authRequired: false,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          email: 'founder@acmerobotics.dev',
          password: 'Password123#Secure',
        }, null, 2),
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-auth-me',
        name: 'Get Authenticated User Profile',
        method: 'GET',
        path: '/api/v1/auth/me',
        summary: 'Retrieve current user profile, organization ID, and RBAC roles',
        resource: 'Profile',
        authRequired: true,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Authorization', 'Bearer {{jwt_token}}']]),
        requestBody: '',
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-auth-refresh-saas',
        name: 'Refresh Access Token',
        method: 'POST',
        path: '/api/v1/auth/refresh',
        summary: 'Exchange expired session token for fresh JWT token',
        resource: 'Authentication',
        authRequired: false,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          refreshToken: 'rt_88b19a0ceb31908efc',
        }, null, 2),
        mockScenario: 200,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'ep-auth-invite',
        name: 'Invite Member to Workspace',
        method: 'POST',
        path: '/api/v1/organization/invites',
        summary: 'Send email invitation with assigned role (admin/member/viewer)',
        resource: 'Organization',
        authRequired: true,
        queryParams: [],
        pathParams: [],
        headers: makeKV([['Authorization', 'Bearer {{jwt_token}}'], ['Content-Type', 'application/json']]),
        requestBody: JSON.stringify({
          email: 'devops.lead@acmerobotics.dev',
          role: 'admin',
          team: 'Infrastructure',
        }, null, 2),
        mockScenario: 201,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
];
